### ISSUE TITLE
Unable to lint project w/ npm run lint

### ISSUE THREAD

**Issue by RyanGrieb** [excaliburjs/Excalibur#2489]
### Steps to Reproduce
Run `npm run lint`

### Expected Result
No errors

### Actual Result
```npm run lint

> excalibur@0.27.0 lint
> npm run eslint && npm run eslint:spec


> excalibur@0.27.0 eslint
> eslint "src/engine/**/*.ts"


Oops! Something went wrong! :(

ESLint: 8.21.0

/home/ryan/Documents/Coding/Excalibur/node_modules/eslint-plugin-jsdoc/dist/iterateJsdoc.js:278
  })() ?? jsdoc.source.findIndex(({
        ^

SyntaxError: Unexpected token '?'
    at new Script (vm.js:88:7)
    at NativeCompileCache._moduleCompile (/home/ryan/Documents/Coding/Excalibur/node_modules/v8-compile-cache/v8-compile-cache.js:240:18)
    at Module._compile (/home/ryan/Documents/Coding/Excalibur/node_modules/v8-compile-cache/v8-compile-cache.js:184:36)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (/home/ryan/Documents/Coding/Excalibur/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/home/ryan/Documents/Coding/Excalibur/node_modules/eslint-plugin-jsdoc/dist/rules/checkAccess.js:8:44)
    at Module._compile (/home/ryan/Documents/Coding/Excalibur/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
```

### Environment
Ubuntu Linux

- browsers and versions: 
- operating system: 
- Excalibur versions: 
- (anything else that may be relevant)

**Comment by eonarheim** [comment]
@RyanGrieb Wild, not sure why that's happening. What version of node are you running?

**Comment by RyanGrieb** [comment]
> @RyanGrieb Wild, not sure why that's happening. What version of node are you running?

v12.22.9

**Comment by eonarheim** [comment]
Interesting, theoretically that version is supported by `eslint` according to their readme https://github.com/eslint/eslint

Node 16.15.0 seems to working for me. Upgrading Node might be a workaround for you? I think the nullish `??` operator was added to Node in 14.x

It seems related to the jsdoc plugin `eslint-plugin-jsdoc` based on the stacktrace.

**Comment by eonarheim** [comment]
Closing we haven't had any more reports
